# fly.toml app configuration file generated for hydrangea-weather on 2023-08-23T11:36:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hydrangea-weather"
primary_region = "ord"

[build]

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
